void gotoxy(int x,int y);
void ocultarCursor();
void setColor(int color);
void llenarTitulo();
void llenarFantasmas();
void llenarTeclado();
void llenarFantasmasAzules();
void llenarMapa();
void imprimirSpace();
void teclearMenu();
void teclear();
void menu();
void marcadorFijo();
void marcador();
void imprimirPacman(int i , int j);
void borrarPacman(int i, int j);
void puntosComida(int i, int j);
void movArribaPacman(int &i, int &j);
void movAbajoPacman(int &i, int &j);
void movIzquierdaPacman(int &i, int &j);
void movDerechaPacman(int &i, int &j);
void movPasadizoIzq(int &i, int &j);
void movPasadizoDer(int &i, int &j);
void mover(int &i, int &j);
void imprimirClyde(int iC , int jC);
void  imprimirComidaClyde(int iC, int jC, char movClyde);
void borrarClyde(int iC, int jC);
void randomClyde(int &movClydeAux, char &movClyde);
void movArribaClyde(int &iC, int &jC, int &movClydeAux, char &movClyde);
void choqueClyde(int &i, int &j, int &iC, int &jC, int &dir, char movClyde, int anteriorpi, int anteriorpj);
void movAbajoClyde(int &iC, int &jC, int &movClydeAux, char &movClyde);
void movIzquierdaClyde(int &iC, int &jC, int &movClydeAux, char &movClyde);
void movDerechaClyde(int &iC, int &jC, int &movClydeAux, char &movClyde);
void moverClyde(int &iC, int &jC, char &movClyde,int &movClydeAux);
void imprimirBlinky(int iB , int jB);
void borrarBlinky(int iB, int jB);
void movIzquierdaBlinky(int &iB, int &jB, int i, int j);
void movDerechaBlinky(int &iB, int &jB, int i, int j);
void movArribaBlinky(int &iB, int &jB, int i, int j);
void movAbajoBlinky(int &iB, int &jB, int i, int j);
void moverBlinky(int &iB, int &jB, int i, int j, int dir);
void imprimirPinky(int iP , int jP);
void imprimirInky(int iI , int jI);
void menuYouWin();
void menuYouLose();
void menu();